node('java8') {
   
    stage('Clone') {
        git credentialsId: 'github-doterob', url: 'https://github.com/doterob/airport'
    }
    
    stage('Build') {
        sh 'mvn clean package install -Dmaven.test.failure.ignore=true'
    }
    
    stage('Junit'){
        junit '**/target/surefire-reports/*.xml'
    }
    
    stage('Integration'){
        sh 'mvn clean integration-test -P integration-test'
        junit '**/target/failsafe-reports/*.xml'
    }
    
    stage('Sonar') {
        sh 'mvn sonar:sonar -Dsonar.host.url=http://192.168.1.39:9000'
    }
    
    stage('Result') {
        archive includes: '**target/*.war'
    }
}